import './globals.css';
import { Navbar } from './components/nav-bar';
import { Inter } from 'next/font/google';
import { cookies } from "next/headers";
import SupabaseListener from './components/supabase-listener';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { Database } from '@/database.types';
import { redirect } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: '大丸白衣在庫',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient<Database>({ cookies });
  const { data: { session } } = await supabase.auth.getSession();

  return (
    <html lang="ja">
      <body className={`${inter.className} bg-neutral-100` }>
        {/* <SupabaseListener /> */}
        <Navbar session={session} />
        {children}
      </body>
    </html>
  );
}
